version: "3.4"
services:
    tedicross:
        build: .
        working_dir: /app
        environment:
            - NODE_ENV=production
        command: "npm start"
        secrets:
            - source: tedicross-settings.yaml
              target: /app/settings.yaml
secrets:
    tedicross-settings.yaml:
        external: true
