version: "3.4"
services:
    tedicross:
        image: tsunderechen/tedicross-docker
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        working_dir: /app
        command: "npm start"
        secrets:
            - source: tedicross-settings.yaml
              target: /app/settings.yaml
              mode: 0666
secrets:
    tedicross-settings.yaml:
        external: true
