version: "3.4"
services:
    tedicross:
        image: tsunderechen/tedicross-docker
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        working_dir: /app
        command: "npm start"
        configs:
            - source: TediCross-Config
              target: /app/settings.yaml
              mode: 0666
configs:
    TediCross-Config:
        external: true
